### ISSUE TITLE
Integrate new popup menu (update to bpmn-js@11.0.0)

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js-color-picker#10]
__What should we do?__

Update to `bpmn-js@11.0.0` and make the adjustments necessary for the new popup menu.

__Why should we do it?__

To ensure the look of the color picker works with the new popop menu UI.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-color-picker/pull/14.
