### ISSUE TITLE
Apply colour background instead of only colouring the border?

### ISSUE THREAD

**Issue by vesper8** [bpmn-io/bpmn-js-color-picker#16]
Am I missing something? Is this addon only meant to color the border around tasks/events?

Is it not also possible to fill the background itself too?

I know it's possible to do it using this prototype https://github.com/bpmn-io/bpmn-js-nyan/tree/master/lib/color-picker

Any plans to add this option to https://github.com/bpmn-io/bpmn-js-color-picker ?

Many thanks!

**Comment by nikku** [comment]
Please use our existing issue template. Establish full context and, if you file a bug, provide clear steps to reproduce.

We cannot help you otherwise.
