### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by shibaaboy** [bpmn-io/bpmn-js-color-picker#17]
I am using bpmn-js. I want to add custom colors in palette. Can i add my own colors to this palette ? If you can add custom colors, you can show an example  ?

**Comment by marstamm** [comment]
Hi @shibaaboy ,

You can customize the colors by providing them as config options when creating your modeler. This will override the default colors, which are defined here: https://github.com/bpmn-io/bpmn-js-color-picker/blob/master/colors/ColorPopupProvider.js#L5-L29

You can supply your config to the modeler like this: 
```JS
const modeler = new Modeler({
  container,
  additionalModules: [BpmnColorPickerModule],
  colorPicker: {
    colors: [
      {
        label: "Default",
        fill: undefined,
        stroke: undefined
      },
      {
        label: "Black",
        fill: "#333",
        stroke: "#000"
      }
    ]
  }
});
```
Cf. Codemirror example page: https://codesandbox.io/s/frosty-archimedes-coglzj?file=/src/index.js:427-780

For general and implementation questions, our [forum](https://forum.bpmn.io/) is better handled to have discussions than the Github issues 😄 

Cheers!

**Comment by shibaaboy** [comment]
thanks!
