### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by Imran-Haider313** [bpmn-io/bpmn-js-color-picker#3]
__Describe the Bug__
I created new reactJs project to apply BPMN.IO

I have this package.json file
```
"dependencies": {
    "bpmn-font": "^0.10.0",
    "bpmn-js": "^7.4.0",
    "bpmn-js-in-color": "github:bpmn-io/bpmn-js-in-color",
    "diagram-js-minimap": "^2.0.3",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
    "tiny-svg": "^2.2.2",
    "web-vitals": "^0.2.4"
  }
```
In my App.js

```
import React, { Fragment, Component } from "react";
import BpmnModeler from "bpmn-js/lib/Modeler";
import { emptyBpmn } from "./diagram.bpmn.jsx";
import bpmnJsInColor from "bpmn-js-in-color";
import minimapModule from "diagram-js-minimap";

import "./vendor/diagram-js.css";
import "bpmn-font/dist/css/bpmn-embedded.css";
import "diagram-js-minimap/assets/diagram-js-minimap.css";

class App extends Component {
  modeler = null;

  saveModelHandler = (event) => {
    event.preventDefault();
  };

  componentDidMount = () => {
    this.modeler = new BpmnModeler({
      container: "#bpmnview",
      additionalModules: [require("bpmn-js-in-color")],
      keyboard: { bindTo: document },
    });

    this.newBpmnDiagram();
  };

  newBpmnDiagram = () => {
    this.openBpmnDiagram(emptyBpmn);
  };

  openBpmnDiagram = async (xml) => {
    await this.modeler.importXML(xml);
    var canvas = this.modeler.get("canvas");
    canvas.zoom("fit-viewport");
  };

  render = () => {
    return (
      <Fragment>
        <div
          id="bpmnview"
          style={{ width: "100%", height: "100vh", float: "left" }}
        ></div>
      </Fragment>
    );
  };
}

export default App;

```

When I enter `npm start`. It throws error
```
 **TypeError: Object prototype may only be an Object or null: undefined**
inherits
**node_modules/inherits/inherits_browser.js:6**
  3 | module.exports = function inherits(ctor, superCtor) {
  4 |   if (superCtor) {
  5 |     ctor.super_ = superCtor
> 6 |     ctor.prototype = Object.create(superCtor.prototype, {
    | ^  7 |       constructor: {
  8 |         value: ctor,
  9 |         enumerable: false,

```

__Environment__

- Host (Browser/Node version),[Macbook pro, Chrome 69, Node v14.4.0 LTS]
- Library version: [e.g. 2.0.0]

---

Also [mentioned in forum](https://forum.bpmn.io/t/bpmn-js-in-color-error/6490).

**Comment by philippfromme** [comment]
This is an example repository, not a package that you can import. If you have any more questions regarding colors in bpmn-js please head over to the [forum](https://forum.bpmn.io/).

**Comment by Imran-Haider313** [comment]
I understand your point. But then why the following is mentioned in doc

Fetch bpmn-js-in-color as a dependency:

`npm install bpmn-io/bpmn-js-in-color --save`
Extend your BPMN modeler with colors:

```
var BpmnModeler = require('bpmn-js/lib/Modeler');

var modeler = new BpmnModeler({
  additionalModules: [
    require('bpmn-js-in-color')
  ]
});
```

**Comment by philippfromme** [comment]
Ignore my comment. I didn't know that this was actually released as a package.

The issue that I found is that this package is still using CommonJS which doesn't play well with default imports. The error that you're seeing is a result of

```javascript
// ColorRenderer.js

var BpmnRenderer = require('bpmn-js/lib/draw/BpmnRenderer');
```

which actually imports

```javascript
{
  default: BpmnRenderer()
}
```

Example: https://codesandbox.io/s/bpmn-js-in-color-error-l0rre?file=/src/index.js

If you want to use colors I'd recommend using the [`Modeling#setColor`](https://github.com/bpmn-io/bpmn-js/blob/v7.4.1/lib/features/modeling/Modeling.js#L183) API that was built for this purpose.

**Comment by Imran-Haider313** [comment]
I check [setColor](https://forum.bpmn.io/t/bpmn-js-add-color-to-modeler-elements/3241/4?u=imran_naqvi) but I don't get what is element1 & element2 in docs. I'm using ReactJs for my project. Is there any documentation for that

**Comment by philippfromme** [comment]
This has nothing to with React. For further questions please stick to the [forum](forum.bpmn.io).

**Comment by nikku** [comment]
It should now be possible to use the color picker in latest versions of bpmn-js.

For that purpose we also renamed it to `bpmn-js-color-picker` to provide more clarity on what it does.
