### ISSUE TITLE
Is it possible to only have the color picker available on bpmn:Task elements? See my current solution

### ISSUE THREAD

**Issue by vesper8** [bpmn-io/bpmn-js-color-picker#31]
This is the code I came up with that hides the color picker on all elements except bpmn:Task. But it causes a micro-flicker. Is there a better way? If you remove the setTimeout below then it does not work.

```

export default function SelectiveColorPicker(modeler) {
  const eventBus = modeler.get('eventBus');

  // Intercept the display of the context pad
  eventBus.on('contextPad.create', function (event) {
    if (event.target.type !== 'bpmn:Task') {
      setTimeout(() => {
        const colorPickerEntry = event.pad.html.querySelector('[data-action="set-color"]');

        if (colorPickerEntry) {
          colorPickerEntry.style.display = 'none';
        }
      });
    }
  });
}
```

**Comment by nikku** [comment]
You'd want to override the default `colorContextPadProvider` with your custom version, a subclass of [`ColorContextPadProvider`](https://github.com/bpmn-io/bpmn-js-color-picker/blob/main/colors/ColorContextPadProvider.js) that [only returns the entry](https://github.com/bpmn-io/bpmn-js-color-picker/blob/main/colors/ColorContextPadProvider.js#L35) for `bpmn:Task` elements.
