### ISSUE TITLE
color picker popup positioning only works when diagram is full screen or in the top left corner

### ISSUE THREAD

**Issue by vesper8** [bpmn-io/bpmn-js-color-picker#40]
If the bpmn-js diagram is not in the top left corner, then the color picker popup positions itself as if it was in the top left corner regardless of where it actually is.

I believe this is because of this line https://github.com/bpmn-io/bpmn-js-color-picker/blob/af77cfb8593d4ce78a3831fc540d8542e2796ed5/colors/ColorContextPadProvider.js#L77

I was able to work around the problem with this hack

```

      const correctPopupMenuPosition = () => {
        const popup = document.querySelector('.djs-popup');
        if (popup) {
          const selection = modeler.get('selection');
          const currentElement = selection.get();

          if (currentElement.length) {
            const element = currentElement[0];
            const gfx = modeler.get('elementRegistry').getGraphics(element);
            const elementBBox = gfx.getBoundingClientRect();

            const offsetX = 30; // Adjust as needed
            const offsetY = 5; // Adjust as needed

            popup.style.left = `${elementBBox.right + offsetX}px`;
            popup.style.top = `${elementBBox.top - offsetY}px`;
          }
        }
      };

      // Correct the popup position when it's opened
      modeler.on('popupMenu.open', function () {
        setTimeout(correctPopupMenuPosition, 0);
      }, 1000);

      // Reapply position corrections if the popup changes its style
      const observer = new MutationObserver((mutations) => {
        mutations.forEach((mutation) => {
          if (mutation.attributeName === 'style') {
            correctPopupMenuPosition();
          }
        });
      });

      // Observe the popup for style changes
      document.addEventListener('mouseover', function (e) {
        if (e.target.closest('.djs-popup')) {
          observer.observe(document.querySelector('.djs-popup'), { attributes: true });
        }
      });

      // Disconnect the observer when the popup is closed
      modeler.on('popupMenu.close', function () {
        observer.disconnect();
      });
```

**Comment by barmac** [comment]
I can reproduce this problem. Thanks for reporting.

https://github.com/bpmn-io/bpmn-js-color-picker/assets/28307541/e6c3e73f-16f0-4fb0-b9df-4cd98d54333a

**Comment by vesper8** [comment]
@barmac I have submitted a PR. I've simplified the positioning method quite a bit.. and this now works perfectly for me in all scenarios (multiple diagrams on the same page, diagram is not in top left).

Cheers!

**Comment by nikku** [comment]
Released fix via `v0.7.1`

**Comment by IRRDC** [comment]
Works like a charm. Thank you @vesper8

**Comment by vesper8** [comment]
Cheers. Glad I could help. Gotta say though I much prefer my positioning where the colour picker appears on top of the context pad rather than below it. So I think I'll keep using my version.

**Comment by nikku** [comment]
> Gotta say though I much prefer my positioning where the colour picker appears on top of the context pad rather than below it. 

We consider to change this one day, but doing so we want to align it across different popup editors that we host :).
