### ISSUE TITLE
Example: The color picker does not appear

### ISSUE THREAD

**Issue by djalilhebal** [bpmn-io/bpmn-js-color-picker#43]
### Describe the Bug

The color picker does not appear even if you include the module. This issue also occurs in the included example.

![image](https://github.com/user-attachments/assets/c84dd63a-062d-49ab-b727-67df4f7f243a)

### Steps to Reproduce

1. Clone the repo
2. `npm i && npm start`
3. Open the example page (automatically opens by default)

### Expected Behavior

There is no way to change the color of a specific shape.

### Environment

- Host (Browser/Node version), if applicable: Chrome 128, Node 20.11
- OS: Ubuntu 22.04
- Library version: 0.7.1
- bpmn-js: 14.x, 17.0.0, 17.9.2 (updated `package.json` to test different versions)

**Comment by barmac** [comment]
I just cloned the repo, installed the dependencies, started an example, and was able to change the color:

https://github.com/user-attachments/assets/5e760a10-bfac-455f-8da3-14d2799439c0
